# Generated by Django 4.2.8 on 2024-09-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(default='kalai', max_length=100),
            preserve_default=False,
        ),
    ]
